<?php


namespace Blankphp\Kernel;


use Blankphp\Provider\Provider;

class AppServiceProvider extends Provider
{

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function register()
    {
        //并不是核心的核心
        parent::register(); // TODO: Change the autogenerated stub
    }
}