<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/3/14
 * Time: 16:43
 */

namespace Blankphp\Config;


use Blankphp\Provider\Provider;

class ConfigServiceProvider extends Provider
{

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }


}