<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/3/14
 * Time: 9:04
 */

namespace Blankphp\Provider;

class MiddleWareProvider extends Provider
{

    protected $namespace = 'App\Middleware';
    protected $middleware = [

    ];
    protected $registerMiddleware;
    protected $groupMiddleware=[];
    public function getMiddleware($group){
        //写出= =要加载的文件或者config中的中间件
        if (isset($this->groupMiddleware[$group]))
            return $this->groupMiddleware[$group];
    }

    public function boot()
    {
//        $this->app->bind('middleware', $this);
        $this->app->signal('GroupMiddleware', $this->groupMiddleware);
        $this->app->signal('AliceMiddleware', $this->registerMiddleware);
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }


    public function getAliceMiddleWare($alice){
        $temp=[];
        foreach ($alice as $item)
            if (isset($this->registerMiddleware[$item]))
                $temp[]=$this->registerMiddleware[$item];
        return $temp;

//        throw new \Exception('not have this middleware '.$alice,1);
    }

}